### ISSUE TITLE
Adding links to elements will break the export

### ISSUE THREAD

**Issue by GordianDziwis** [oeg-upm/Chowlk#53]
After adding a link to a box this happens:

```
Traceback (most recent call last):
  File "converter.py", line 49, in <module>
    main(args.diagram_path, args.output_path, args.type, args.format)
  File "converter.py", line 11, in main
    ontology_turtle, ontology_xml, namespaces, errors = transform_ontology(root)
  File "/home/beavis/repositories/Chowlk/source/chowlk/transformations.py", line 15, in transform_ontology
    concepts, attribute_blocks, relations, individuals, anonymous_concepts, hexagons, metadata, namespaces, rhombuses, errors, anonimous_classes = finder.find_elements()
  File "/home/beavis/repositories/Chowlk/source/chowlk/finding.py", line 1306, in find_elements
    relations = self.find_relations()
  File "/home/beavis/repositories/Chowlk/source/chowlk/finding.py", line 69, in find_relations
    elif id == child2.attrib["parent"]:
KeyError: 'parent'
```

**Comment by Sergio-Carulli** [comment]
Can you send us an example of the input diagram? For example, instead of defining a class through a namespace, it is possible to define it by typing directly the URI
![image](https://github.com/oeg-upm/Chowlk/assets/60430333/1f731f3b-5f53-4550-b5ec-2029845185e3)

**Comment by GordianDziwis** [comment]
I meant, adding a link to the box with a right click and selecting the corresponding menu entry.
